import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../frontend/package.json',import.meta.url));
const ts=require('typescript');
const source=readFileSync(new URL('../frontend/src/utils/faceitBridgeState.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const module={exports:{}};
new Function('module','exports',compiled)(module,module.exports);
const {bridgeMatchState}=module.exports;
const imported={id:'1',match_id:'match',state:'done',demo_file:'nuke.dem',error:null};
const failed={id:'old',state:'error',error:'Extension stopped',kind:'download'};
assert.equal(bridgeMatchState([imported],failed).label,'1 imported');
assert.equal(bridgeMatchState([imported],failed).error,null,'A stale download error must not override a usable replay');
assert.equal(bridgeMatchState([imported,{...imported,id:'duplicate'}],failed).demos.length,1);
assert.equal(bridgeMatchState([imported],{...failed,expected_count:2}).label,'1 imported · incomplete');
assert.equal(bridgeMatchState([],failed).tone,'error');
assert.equal(bridgeMatchState([],{...failed,state:'running',error:null,stage:'reading_demo_links'}).label,'Reading demo links…');
assert.equal(bridgeMatchState([imported,{...imported,id:'2',state:'importing',demo_file:null}],failed).label,'1 imported · Analysing demo…');
console.log('FACEIT library state: success, stale errors, partial series, progress and duplicates passed.');
