import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../frontend/package.json',import.meta.url));
const ts=require('typescript');
const source=readFileSync(new URL('../frontend/src/api/replayCache.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const mod={exports:{}};
new Function('module','exports',compiled)(mod,mod.exports);
const {cachedReplay,invalidateReplay}=mod.exports;
let loads=0;
const timeline={positions:{one:[{t:1}]},rounds:[]};
const load=async()=>{loads++;return {timeline,revision:'v1'};};
const [one,two]=await Promise.all([cachedReplay('one','v1',load),cachedReplay('one','v1',load)]);
assert.equal(loads,1,'Concurrent loads are deduplicated');
assert.equal(one,two);
assert.equal(await cachedReplay('one','v1',load),timeline,'Revisit reuses the original object, without parsing JSON');
assert.equal(loads,1);
await cachedReplay('one','v2',async()=>{loads++;return {timeline:{...timeline},revision:'v2'};});
assert.equal(loads,2,'Changed revision reloads');
await invalidateReplay('one');
await cachedReplay('one','v2',async()=>{loads++;return {timeline,revision:'v2'};});
assert.equal(loads,3,'Explicit reparse/upload/delete invalidate cache');
let finish;
const stale=cachedReplay('pending','v1',()=>new Promise(r=>{finish=r;}));
await new Promise(r=>setImmediate(r));
await invalidateReplay('pending');
finish({timeline,revision:'v1'});await stale;
let refreshed=false;
await cachedReplay('pending','v1',async()=>{refreshed=true;return {timeline,revision:'v1'};});
assert.ok(refreshed,'Invalidation during an outstanding load cannot populate the memory cache');
for(const key of ['a','b','c']) await cachedReplay(key,'v1',load);
const before=loads;await cachedReplay('a','v1',load);
assert.equal(loads,before+1,'The LRU cache is bounded');
console.log('Replay cache: revisits, request deduplication, revisions, invalidation, in-flight invalidation and LRU passed.');
const restricted={exports:{}};
new Function('module','exports','indexedDB',compiled)(restricted,restricted.exports,{open(){throw new Error('Private browsing blocked IndexedDB');}});
assert.equal(await restricted.exports.cachedReplay('private','v1',load),timeline,'Unavailable disk caching must never block playback');
await restricted.exports.invalidateReplay('private');
let failures=0;
await assert.rejects(cachedReplay('failed','v1',async()=>{failures++;throw new Error('offline');}));
await cachedReplay('failed','v1',async()=>{failures++;return {timeline,revision:'v1'};});
assert.equal(failures,2,'Failed loads can be retried');
console.log('Replay cache: private-mode fallback and failed-load retry passed.');
